apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nodejs-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-nodejs-webapp
  template:
    metadata:
      labels:
        app: simple-nodejs-webapp
    spec:
      containers:
      - name: simple-nodejs-webapp
        image: soggen83/simple-nodejs-webapp
        ports:
        - containerPort: 8080
        env:
        - name: APPLICATION_INSTANCE
          value: "example"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /example/health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /example/health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
