apiVersion: v1
kind: Service
metadata:
  name: simple-nodejs-webapp-service
spec:
  selector:
    app: simple-nodejs-webapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
